#pragma once

#define D_DESIGN_WIDTH	800
#define D_DESIGN_HEIGHT 1280

#define D_WINDOWS_SHOW 0.55

#define D_GAME_NAME "My Game"

// tile
#define TILE_TSIZE 120
#define TILE_XSIZE 6
#define TILE_YSIZE 6

// block
#define BLOCK_YSIZE 50
#define BLOCK_XSIZE 50

#define ORIGINAL_SIZE 1.0f
#define SELECTED_SIZE 1.8f

#define KEY_GOAL_SCORE "GOAL_STAGE"
#define KEY_SLIDE_COUNT "SLIDE_COUNT"
#define KEY_GAME_TIME "GAME_COUNT"
#define KEY_BOOM_COUNT "KEY_BOOM_COUNT"
#define KEY_STAGE_NUM "KEY_STAGE_NUM"